//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capacitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Capacitacion()
        {
            this.CapacitacionxVoluntario = new HashSet<CapacitacionxVoluntario>();
        }
    
        public int iId { get; set; }
        public string vNombre { get; set; }
        public string vDescripcion { get; set; }
        public Nullable<System.DateTime> dtFechaInicio { get; set; }
        public Nullable<System.DateTime> dtFechaFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapacitacionxVoluntario> CapacitacionxVoluntario { get; set; }
    }
}
