//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacitacionxVoluntario
    {
        public int iId { get; set; }
        public Nullable<int> iIdCapacitacion { get; set; }
        public Nullable<int> iIdVoluntario { get; set; }
    
        public virtual Capacitacion Capacitacion { get; set; }
        public virtual Voluntario Voluntario { get; set; }
    }
}
