//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competencia()
        {
            this.EquipoxCompetencia = new HashSet<EquipoxCompetencia>();
            this.VoluntarioxCompetencia = new HashSet<VoluntarioxCompetencia>();
        }
    
        public int iId { get; set; }
        public string vDescripcion { get; set; }
        public Nullable<System.DateTime> dtFechaInicio { get; set; }
        public Nullable<System.DateTime> dtFechaFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoxCompetencia> EquipoxCompetencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoluntarioxCompetencia> VoluntarioxCompetencia { get; set; }
    }
}
