//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSean.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FSeanDB : DbContext
    {
        public FSeanDB()
            : base("name=FSeanDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capacitacion> Capacitacion { get; set; }
        public virtual DbSet<CapacitacionxVoluntario> CapacitacionxVoluntario { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CategoriaxEquipo> CategoriaxEquipo { get; set; }
        public virtual DbSet<Competencia> Competencia { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<EquipoxCompetencia> EquipoxCompetencia { get; set; }
        public virtual DbSet<Orden> Orden { get; set; }
        public virtual DbSet<Participante> Participante { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Voluntario> Voluntario { get; set; }
        public virtual DbSet<VoluntarioxCompetencia> VoluntarioxCompetencia { get; set; }
    }
}
