//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public int iId { get; set; }
        public Nullable<int> iIdUsuario { get; set; }
        public Nullable<int> iIdProducto { get; set; }
        public Nullable<int> iCantidad { get; set; }
        public Nullable<decimal> dcPrecioFinal { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
