//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Orden = new HashSet<Orden>();
        }
    
        public int iId { get; set; }
        public Nullable<int> iRol { get; set; }
        public string vUsuario { get; set; }
        public string vContraseña { get; set; }
        public Nullable<int> iIdRol { get; set; }
        public string vNombre { get; set; }
        public string vCorreo { get; set; }
        public string vIdentificacion { get; set; }
        public Nullable<System.DateTime> dtFechaNacimiento { get; set; }
        public Nullable<int> iTelefono { get; set; }
        public Nullable<int> bAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Orden { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
