//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voluntario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voluntario()
        {
            this.CapacitacionxVoluntario = new HashSet<CapacitacionxVoluntario>();
            this.VoluntarioxCompetencia = new HashSet<VoluntarioxCompetencia>();
        }
    
        public int iId { get; set; }
        public string vLugarTrabajo { get; set; }
        public string vAreaConocimiento { get; set; }
        public Nullable<bool> bAntiguedad { get; set; }
        public Nullable<int> iRoles { get; set; }
        public string vExperienciaPasada { get; set; }
        public string vSugerencias { get; set; }
        public string vArea { get; set; }
        public Nullable<int> iCategoria { get; set; }
        public string vEncargado { get; set; }
        public Nullable<bool> bJuez { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapacitacionxVoluntario> CapacitacionxVoluntario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoluntarioxCompetencia> VoluntarioxCompetencia { get; set; }
    }
}
